CREATE TABLE IF NOT EXISTS urls(
id SERIAL PRIMARY KEY,
name VARCHAR(255) UNIQUE NOT NULL,
created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS url_checks(
id SERIAL PRIMARY KEY,
url_id INT REFERENCES urls(id) NOT NULL,
status_code INT NOT NULL,
h1 TEXT NOT NULL,
title TEXT NOT NULL,
description TEXT NOT NULL,
created_at TIMESTAMP DEFAULT NOW() NOT NULL
);
